[package]
name = "photo_framer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive", "wrap_help"] }
env_logger = "0.11.8"
exitcode = "1.1.2"
image = "0.25.6"
log = "0.4.27"
